### PR TITLE
Remove Nonstatic Zip & Reqwest

### PR DESCRIPTION
**Pull request by lolpro11**
This does not affect the functionality of the crate, as this does not use zstd. Same thing with using rust-tls. We are just switching tls libraries.
These changes will allow a static compile of this library.

### CODE REVIEW

**Review by antoine-de — APPROVED** [review]
fine for me, thanks for this!

**Comment by Tristramg** [comment]
I’d be a bit more cautious concerning the compression algorithm support. We use zip to read files generated by others.
It would be annoying if there are some zip files that can not be read anymore; multiple formats seem to used, not only deflate: https://en.wikipedia.org/wiki/ZIP_(file_format)#Compression_methods

No problem for rust-tls

**Comment by lolpro11** [comment]
Update: I patched zip to use only Rust versions of bzip2 and zstd, thereby allowing rustc to compile this lib statically

**Comment by antoine-de** [comment]
We cannot depend directly on a git dependency, we need something properly published on crates.io

By curiosity, would do you need this?

**Comment by lolpro11** [comment]
> We cannot depend directly on a git dependency, we need something properly published on crates.io
> 
> By curiosity, would do you need this?

I am waiting on an upstream PR with zip. Also, I do need this so I can run this in a container

**Comment by kylerchin** [comment]
> We cannot depend directly on a git dependency, we need something properly published on crates.io
> 
> By curiosity, would do you need this?

I completely agree with this.

**Comment by lolpro11** [comment]
> I’d be a bit more cautious concerning the compression algorithm support. We use zip to read files generated by others. It would be annoying if there are some zip files that can not be read anymore; multiple formats seem to used, not only deflate: https://en.wikipedia.org/wiki/ZIP_(file_format)#Compression_methods
> 
> No problem for rust-tls

Store (no compression),
Shrink (LZW),
Reduce (levels 1–4; LZ77 + probabilistic),Implode, Deflate, Deflate64, bzip2, LZMA, WavPack, PPMd, and a LZ77 variant provided by IBM z/OS CMPSC instruction.

**Comment by dkter** [comment]
I patched it to allow disabling of bzip and zstd via a feature, this shouldn't break anything by default since the feature is enabled by default: https://github.com/dkter/gtfs-structure/commit/cf418953684dd9ab286857d457689117095bad82

**Comment by lolpro11** [comment]
> I patched it to allow disabling of bzip and zstd via a feature, this shouldn't break anything by default since the feature is enabled by default: [dkter@cf41895](https://github.com/dkter/gtfs-structure/commit/cf418953684dd9ab286857d457689117095bad82)
> 
> If needed I can make another PR

Can you make another PR for this? That would be great. Also, what do you intend on doing for rust-tls?

**Comment by dkter** [comment]
> Also, what do you intend on doing for rust-tls?

I'm able to use default-tls for my use case but could re-export these if helpful?

```
reqwest-default = ["reqwest/default"]
reqwest-rustls = ["reqwest/rustls"]
reqwest-http2 = ["reqwest/http2"]
```

**Comment by lolpro11** [comment]
>
> I'm able to use default-tls for my use case but could re-export these if helpful?
> 
> ```
> reqwest-default = ["reqwest/default"]
> reqwest-rustls-tls = ["reqwest/rustls-tls"]
> ```

Yeah, that looks good! Thanks. Let me know when you have the PR done so I can close this one.

**Comment by dkter** [comment]
#163

**Pull request closed without merging**
